//! Metadata from OrcaSlicer-family G-code. The per-tool filament summary and the settings
//! block sit after the moves, so only the head and tail of a file are read.

use std::{io::SeekFrom, path::Path};

use thiserror::Error;
use tokio::io::{AsyncReadExt, AsyncSeekExt};

use crate::inventory;

pub const HEAD_BYTES: u64 = 16 * 1024;
/// The settings block of a multi-material file is around 26 KB, and the summary sits just
/// before it.
pub const TAIL_BYTES: u64 = 256 * 1024;

#[derive(Debug, Clone, PartialEq)]
pub struct GcodeInfo {
    /// `OrcaSlicer 2.4.2`, from the `generated by` line.
    pub generator: String,
    pub printer_model: String,
    pub nozzle: String,
    /// The build plate type the bed is heated for, as OrcaSlicer names it; empty when the file
    /// gives none.
    pub plate: String,
    pub estimated_seconds: Option<i64>,
    pub layers: Option<i64>,
    /// One entry per slicer filament, including ones no object uses.
    pub tools: Vec<ToolUse>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ToolUse {
    /// The `T` number in the moves, and `t` in the printer's `slot_map`.
    pub index: u32,
    pub material: String,
    /// `#RRGGBB`, or empty when the file gives none.
    pub color: String,
    pub grams: f64,
    pub profile: String,
}

impl GcodeInfo {
    pub fn used_tools(&self) -> impl Iterator<Item = &ToolUse> {
        self.tools.iter().filter(|tool| tool.grams > 0.0)
    }

    pub fn total_grams(&self) -> f64 {
        self.used_tools().map(|tool| tool.grams).sum()
    }

    /// The nozzle diameter, when the file names one and every extruder has the same.
    pub fn nozzle_mm(&self) -> Option<f64> {
        let mut diameters = self
            .nozzle
            .split([',', ';'])
            .map(|diameter| diameter.trim().parse::<f64>().ok());
        let first = diameters.next()??;
        diameters.all(|d| d == Some(first)).then_some(first)
    }
}

#[derive(Debug, Error)]
pub enum GcodeError {
    #[error("reading the G-code: {0}")]
    Io(#[from] std::io::Error),
    #[error("this is not sliced G-code: it has no filament summary")]
    NoSummary,
}

pub async fn read(path: &Path) -> Result<GcodeInfo, GcodeError> {
    let mut file = tokio::fs::File::open(path).await?;
    let len = file.metadata().await?.len();

    let mut head = Vec::new();
    (&mut file).take(HEAD_BYTES).read_to_end(&mut head).await?;
    let tail = if len > HEAD_BYTES {
        file.seek(SeekFrom::Start(
            len.saturating_sub(TAIL_BYTES).max(HEAD_BYTES),
        ))
        .await?;
        let mut tail = Vec::new();
        file.read_to_end(&mut tail).await?;
        tail
    } else {
        Vec::new()
    };
    parse(
        &String::from_utf8_lossy(&head),
        &String::from_utf8_lossy(&tail),
    )
}

pub fn parse(head: &str, tail: &str) -> Result<GcodeInfo, GcodeError> {
    let mut settings = std::collections::HashMap::new();
    let mut generator = String::new();
    let mut header_layers = None;
    for line in head.lines().chain(tail.lines()) {
        let Some(comment) = line.strip_prefix("; ") else {
            continue;
        };
        if let Some(rest) = comment.strip_prefix("generated by ") {
            generator = rest.split(" on ").next().unwrap_or(rest).trim().to_owned();
        } else if let Some(layers) = comment.strip_prefix("total layer number: ") {
            header_layers = layers.trim().parse().ok();
        } else if let Some((key, value)) = comment.split_once(" = ") {
            settings.insert(key.trim(), value.trim());
        }
    }

    let numbers = |key: &str| -> Option<Vec<f64>> {
        let raw = settings.get(key)?;
        raw.split(',').map(|n| n.trim().parse().ok()).collect()
    };
    let list = |key: &str| -> Vec<String> {
        settings.get(key).map_or_else(Vec::new, |raw| {
            raw.split(';')
                .map(|item| item.trim().trim_matches('"').to_owned())
                .collect()
        })
    };

    let materials = list("filament_type");
    let grams = match numbers("filament used [g]") {
        Some(grams) => grams,
        // Written only when every filament has a density; derive it from the volume otherwise.
        None => {
            let volumes = numbers("filament used [cm3]").ok_or(GcodeError::NoSummary)?;
            let densities: Vec<f64> = list("filament_density")
                .iter()
                .map(|d| d.parse().unwrap_or(0.0))
                .collect();
            volumes
                .iter()
                .enumerate()
                .map(|(i, cm3)| cm3 * densities.get(i).copied().unwrap_or(0.0))
                .collect()
        }
    };
    if materials.is_empty() && grams.is_empty() {
        return Err(GcodeError::NoSummary);
    }

    let colors = list("filament_colour");
    let profiles = list("filament_settings_id");
    let tools = (0..materials.len().max(grams.len()))
        .map(|i| ToolUse {
            index: u32::try_from(i).unwrap_or(u32::MAX),
            material: materials.get(i).cloned().unwrap_or_default(),
            color: colors
                .get(i)
                .and_then(|c| inventory::normalize_color(c))
                .unwrap_or_default(),
            grams: grams.get(i).copied().unwrap_or(0.0),
            profile: profiles.get(i).cloned().unwrap_or_default(),
        })
        .collect();

    Ok(GcodeInfo {
        generator,
        printer_model: list("printer_model").join(";"),
        nozzle: list("nozzle_diameter").join(";"),
        plate: settings
            .get("curr_bed_type")
            .map_or_else(String::new, |plate| (*plate).to_owned()),
        estimated_seconds: settings
            .get("estimated printing time (normal mode)")
            .and_then(|raw| parse_duration(raw)),
        layers: settings
            .get("total layers count")
            .and_then(|raw| raw.parse().ok())
            .or(header_layers),
        tools,
    })
}

/// `1d 2h 3m 4s`, any part optional, as the slicer writes estimates.
fn parse_duration(raw: &str) -> Option<i64> {
    let mut total = 0i64;
    let mut any = false;
    for part in raw.split_whitespace() {
        let split = part.find(|c: char| !c.is_ascii_digit())?;
        let (number, unit) = part.split_at(split);
        let number: i64 = number.parse().ok()?;
        total += number
            * match unit {
                "d" => 86_400,
                "h" => 3_600,
                "m" => 60,
                "s" => 1,
                _ => return None,
            };
        any = true;
    }
    any.then_some(total)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(name: &str) -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures")
            .join(name)
    }

    /// Sliced by the OrcaSlicer 2.4.2 CLI with the bundled ECC2 0.4 nozzle, 0.20mm Standard
    /// and Elegoo PLA profiles, flattened the way `slicer` does it.
    #[tokio::test]
    async fn single_tool_cube() {
        let info = read(&fixture("orca-2.4.2-cc2-pla-cube.gcode"))
            .await
            .unwrap();
        assert_eq!(info.generator, "OrcaSlicer 2.4.2");
        assert_eq!(info.printer_model, "Elegoo Centauri Carbon 2");
        assert_eq!(info.nozzle, "0.4");
        assert_eq!(info.nozzle_mm(), Some(0.4));
        assert_eq!(info.plate, "Cool Plate", "sliced before the plate was set");
        let mixed = GcodeInfo {
            nozzle: "0.4;0.6".into(),
            ..info.clone()
        };
        assert_eq!(mixed.nozzle_mm(), None);
        assert_eq!(info.estimated_seconds, Some(9 * 60 + 21));
        assert_eq!(info.layers, Some(100));
        assert_eq!(
            info.tools,
            [ToolUse {
                index: 0,
                material: "PLA".into(),
                color: "#F2754E".into(),
                grams: 3.54,
                profile: "Elegoo PLA @ECC2".into(),
            }]
        );
    }

    /// Two cubes on two PLA filaments. The moves between the head and the summary were cut
    /// from the fixture to keep it small; the parser never reads them.
    #[tokio::test]
    async fn two_tools() {
        let info = read(&fixture("orca-2.4.2-cc2-two-pla.gcode"))
            .await
            .unwrap();
        assert_eq!(info.estimated_seconds, Some(3600 + 30 * 60 + 34));
        assert_eq!(info.layers, Some(75));
        let summary: Vec<_> = info
            .tools
            .iter()
            .map(|t| (t.index, t.color.as_str(), t.grams, t.profile.as_str()))
            .collect();
        assert_eq!(
            summary,
            [
                (0, "#F2754E", 3.89, "Elegoo PLA @ECC2"),
                (1, "#2850DF", 3.96, "Elegoo PLA Blue @ECC2"),
            ]
        );
        assert!((info.total_grams() - 7.85).abs() < 1e-9);
    }

    #[test]
    fn grams_fall_back_to_volume_and_unused_tools_are_kept() {
        let tail = "\
; filament used [mm] = 0.00, 916.48
; filament used [cm3] = 0.00, 2.20
; total filament used [g] = 0.00
; filament_type = PETG;PLA
; filament_density = 1.27;1.25
";
        let info = parse("", tail).unwrap();
        assert_eq!(info.tools.len(), 2);
        assert_eq!(info.used_tools().map(|t| t.index).collect::<Vec<_>>(), [1]);
        assert!((info.tools[1].grams - 2.75).abs() < 1e-9);
        assert_eq!(info.estimated_seconds, None);
    }

    #[test]
    fn plain_text_is_not_gcode() {
        assert!(matches!(
            parse("G28\nG1 X10\n", ""),
            Err(GcodeError::NoSummary)
        ));
    }

    #[test]
    fn durations() {
        assert_eq!(parse_duration("17m 10s"), Some(1030));
        assert_eq!(parse_duration("1d 2h 3m 4s"), Some(93_784));
        assert_eq!(parse_duration("45s"), Some(45));
        assert_eq!(parse_duration("soon"), None);
        assert_eq!(parse_duration(""), None);
    }
}
